// axios的响应输出
{
    status: 200,
    statusText: 'OK',
    headers: {
        date: 'Mon, 16 Jul 2018 09:39:50 GMT',
        server: 'Apache/2.4.33 (Win32) OpenSSL/1.1.0h PHP/7.2.6',
        'x-powered-by': 'PHP/7.2.6',
        'content-length': '21',
        connection: 'close',
        'content-type': 'text/html; charset=UTF-8'
    },
    config: {
        adapter: [Function: httpAdapter],
        transformRequest: { '0': [Function: transformRequest] },
        transformResponse: { '0': [Function: transformResponse] },
        timeout: 0,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        validateStatus: [Function: validateStatus],
        headers: {
            Accept: 'application/json, text/plain, */*',
            'Content-Type': 'application/x-www-form-urlencoded',
            'User-Agent': 'axios/0.18.0',
            'Content-Length': 13
        },
        method: 'post',
        url: 'http://127.0.0.1/JCYD_PHP/index.php',
        data: 'action=select'
    },
    request: ClientRequest {
        domain: null,
        _events: {
            socket: [Function],
            abort: [Function],
            aborted: [Function],
            error: [Function],
            timeout: [Function],
            prefinish: [Function: requestOnPrefinish]
        },
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: Socket {
            connecting: false,
            _hadError: false,
            _handle: null,
            _parent: null,
            _host: null,
            _readableState: [Object],
            readable: false,
            domain: null,
            _events: [Object],
            _eventsCount: 8,
            _maxListeners: undefined,
            _writableState: [Object],
            writable: false,
            allowHalfOpen: false,
            _bytesDispatched: 224,
            _sockname: null,
            _pendingData: null,
            _pendingEncoding: '',
            server: null,
            _server: null,
            parser: null,
            _httpMessage: [Circular],
            _idleNext: null,
            _idlePrev: null,
            _idleTimeout: -1,
            [Symbol(asyncId)]: 28,
            [Symbol(bytesRead)]: 237
        },
        connection: Socket {
            connecting: false,
            _hadError: false,
            _handle: null,
            _parent: null,
            _host: null,
            _readableState: [Object],
            readable: false,
            domain: null,
            _events: [Object],
            _eventsCount: 8,
            _maxListeners: undefined,
            _writableState: [Object],
            writable: false,
            allowHalfOpen: false,
            _bytesDispatched: 224,
            _sockname: null,
            _pendingData: null,
            _pendingEncoding: '',
            server: null,
            _server: null,
            parser: null,
            _httpMessage: [Circular],
            _idleNext: null,
            _idlePrev: null,
            _idleTimeout: -1,
            [Symbol(asyncId)]: 28,
            [Symbol(bytesRead)]: 237
        },
        _header: 'POST /JCYD_PHP/index.php HTTP/1.1\r\nAccept: application/json, text/plain, */*Content - Type: application / x - www - form - urlencoded\ r\ nUser - Agent: axios / 0.18 .0\ r\ nContent - Length: 13\ r\ n        Host: 127.0 .0 .1\ r\ nConnection: close\ r\ n\ r\ n ',
        _onPendingData: [Function: noopPendingOutput],
        agent: Agent {
            domain: null,
            _events: [Object],
            _eventsCount: 1,
            _maxListeners: undefined,
            defaultPort: 80,
            protocol: 'http:',
            options: [Object],
            requests: {},
            sockets: [Object],
            freeSockets: {},
            keepAliveMsecs: 1000,
            keepAlive: false,
            maxSockets: Infinity,
            maxFreeSockets: 256
        },
        socketPath: undefined,
        timeout: undefined,
        method: 'POST',
        path: '/JCYD_PHP/index.php',
        _ended: true,
        res: IncomingMessage {
            _readableState: [Object],
            readable: false,
            domain: null,
            _events: [Object],
            _eventsCount: 3,
            _maxListeners: undefined,
            socket: [Object],
            connection: [Object],
            httpVersionMajor: 1,
            httpVersionMinor: 1,
            httpVersion: '1.1',
            complete: true,
            headers: [Object],
            rawHeaders: [Array],
            trailers: {},
            rawTrailers: [],
            upgrade: false,
            url: '',
            method: null,
            statusCode: 200,
            statusMessage: 'OK',
            client: [Object],
            _consuming: true,
            _dumped: false,
            req: [Circular],
            responseUrl: 'http://127.0.0.1/JCYD_PHP/index.php',
            redirects: [],
            read: [Function]
        },
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        _redirectable: Writable {
            _writableState: [Object],
            writable: true,
            domain: null,
            _events: [Object],
            _eventsCount: 2,
            _maxListeners: undefined,
            _options: [Object],
            _redirectCount: 0,
            _redirects: [],
            _requestBodyLength: 13,
            _requestBodyBuffers: [],
            _onNativeResponse: [Function],
            _currentRequest: [Circular],
            _currentUrl: 'http://127.0.0.1/JCYD_PHP/index.php'
        },
        [Symbol(outHeadersKey)]: {
            accept: [Array],
            'content-type': [Array],
            'user-agent': [Array],
            'content-length': [Array],
            host: [Array]
        }
    },
    data: { num: '2', error: 0 }
}